name: Build and Publish

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the type of runner to use
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify Node.js version

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Build Extension
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Use secret for API key
        run: npm run build  # Replace with your build command

      - name: Package Extension
        run: npx vsce package  # Package your extension

      - name: Publish Extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}  # Use secret for publishing token
        run: npx vsce publish  # Publish your extension
